directories:
  "app/channels":
    IrresponsibleModule:
      enabled: false
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "app/services":
    UtilityFunction:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
  "spec":
    UtilityFunction:
      enabled: false
detectors:
  TooManyInstanceVariables:
    exclude:
      - StateTokenEncoderService
  TooManyStatements:
    exclude:
      - OAuthController#authorize
      - ClientRedirectUrlService#call
      - StateTokenEncoderService#initialize
      - AuthorizationGrantsController#create
      - SessionsController#create
      - SessionsController#url_for_sign_in_redirect
  ControlParameter:
    exclude:
      - ClientAuthentication#http_basic_auth_successful?
  FeatureEnvy:
    exclude:
      - ClientAuthentication#http_basic_auth_successful?
      - AuthorizationGrantsController#create
