directories:
  "app/channels":
    IrresponsibleModule:
      enabled: false
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    UncommunicativeModuleName:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
    Attribute:
      enabled: false
  "app/services":
    UtilityFunction:
      enabled: false
  "db/migrate":
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
  "spec":
    UtilityFunction:
      enabled: false
detectors:
  ControlParameter:
    exclude:
      - ClientAuthentication#http_basic_auth_successful?
  DuplicateMethodCall:
    exclude:
      - API::BaseController#user_from_token
      - OAuth::AuthorizationGrant#redeem
  FeatureEnvy:
    exclude:
      - AuthorizationGrantsController#create
      - ClientAuthentication#http_basic_auth_successful?
  TooManyInstanceVariables:
    exclude:
      - StateTokenEncoderService
  MissingSafeMethod:
    exclude:
      - OAuth::Challenge
  TooManyStatements:
    exclude:
      - ClientRedirectUrlService#call
      - API::BaseController#user_from_token
      - AuthorizationGrantsController#create
      - OAuth::AuthorizationsController#authorize
      - OAuth::AuthorizationGrant#redeem
      - OAuth::Client#url_for_redirect
      - OAuth::SessionsController#token
      - OAuth::SessionCreatable#create_oauth_session
      - OAuth::Session#refresh
      - SessionsController#create
      - SessionsController#url_for_sign_in_redirect
  UtilityFunction:
    exclude:
      - OAuth::SessionCreatable#generate_token
      - OAuth::SessionExchangeable#valid_resource?
      - OAuth::SessionExchangeable#valid_subject_token_type?
