require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/views/**/*'
RSpec/MultipleMemoizedHelpers:
  Max: 15
