require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
Naming/RescuedExceptionsVariableName:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/views/**/*'
RSpec/FilePath:
  Exclude:
    - 'spec/requests/oauth/*'
RSpec/MultipleMemoizedHelpers:
  Max: 15
RSpec/NestedGroups:
  Max: 5
