development:
  issuer_url: 'htt://localhost:3000/'
  access_token_expiration: 5 # In minutes
  refresh_token_expiration: 20160 # In minutes (14 days)
  clients:
    democlient:
      name: 'Demo Client'
      type: 'confidential'
      redirection_uri: 'http://localhost:3000/'

test:
  issuer_url: 'htt://localhost:3000/'
  access_token_expiration: 5 # In minutes
  refresh_token_expiration: 20160 # In minutes (14 days)
  clients:
    democlient:
      name: 'Demo Client'
      type: 'confidential'
      redirection_uri: 'http://localhost:3000/'
    negativetestclient:
      name: 'Negative Test Client'
      type: 'confidential'
      redirection_uri: 'http://localhost:3000/'
